# -*- coding: utf-8 -*-
"""Ex1_TensorFlow overview.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FvfxFj5x8HwhujXjwOjy88GD-kvOp7Ef

Name: Sourabhi Dunung

Roll No: UEC2021211

Class: E&Tc B DL3

Experiment 1: Tensorflow Overwiew
"""

import tensorflow as tf

"""Addition operation"""

a1= tf.constant([[1,2,3],[4,7,13]])
b1= tf.constant([[2,4,7],[5,8,90]])
c1= tf.add(a1,b1)
print(c1)

"""Substraction operation"""

p1= tf.constant([[1,2,3],[4,7,13]])
q1= tf.constant([[2,4,7],[5,8,90]])
r1= tf.subtract(p1,q1)
print(r1)

"""Multiply"""

x1= tf.constant([[1,2,3],[4,7,13]])
y1= tf.constant([[2,4,7],[5,8,90]])
z1= tf.multiply(x1,y1)
print(z1)

"""Matrix Multipilication"""

s1= tf.constant([[1,2,3],[4,7,13]])
t1= tf.constant([[4,7,9],[2,4,7],[5,8,90]])
u1= tf.matmul(s1,t1)
print(u1)

"""row wise or column wise addition"""

l1= tf.constant([[1,2,3],[4,7,13]])
i1=tf.reduce_sum(l1) #complete matrix
i2=tf.reduce_sum(l1,0) #column 1
i3=tf.reduce_sum(l1,1) #column 2
print(i1)
print(i2)
print(i3)

"""declaring the function"""

def myfun():
 print("Hello there!")

myfun()

"""with arguremnt"""

def my_function(fname):
 print(fname + " from cummins")
my_function("Sourabhi")
my_function("Mayuri")
my_function("Nandini")

"""using cProfile"""

import cProfile

def wrapper():
    my_function("Sourabhi")
    my_function("Mayuri")
    my_function("Nandini")

cProfile.run("wrapper()")